### ISSUE TITLE
Cannot find module XYZ or its corresponding type declarations.ts(2307)

### ISSUE THREAD

**Issue by geongeorge** [withastro/language-tools#584]
### What version of `astro` are you using?

2.5.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

I have installed this package, but vscode throws an error when I import it in astro components, but it is working fine inside TSX files. See the screenshots below.

<img width="1151" alt="image" src="https://github.com/withastro/astro/assets/29296982/08ba2484-012f-4f35-a2d3-e1e4e510bf4f">
<img width="568" alt="image" src="https://github.com/withastro/astro/assets/29296982/000dfd6b-e456-4a3b-8ab7-605d9f3b195a">
<img width="1151" alt="image" src="https://github.com/withastro/astro/assets/29296982/35f85ee2-eea5-4834-8a7a-7e0b7757773e">

### Link to Minimal Reproducible Example

https://github.com

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by shishkin** [comment]
I'm having issues in in a project on Astro VS Code extension v2.0.18:

![Screenshot 2023-07-06 at 13 13 16](https://github.com/withastro/language-tools/assets/124065/55e47ba1-552e-4cc5-a1fc-206f47032b12)

It complains about all `*.astro` imports in the project, though everything (build, check, dev) works fine from CLI.

**Comment by Princesseuh** [comment]
I unfortunately cannot debug OP's issue since there's no reproduction, but as for it not working with moduleResolution node16/node ext, it's an upstream issue in Volar

**Comment by arpadgabor** [comment]
Experiencing a similar issue with `.astro` files. On vscode startup everything looks good, but when I create a new component file it no longer loads it inside intellisense until I restart vscode again. Astro runtime and builds are working fine. Will try to share a repro as soon as I can, but for reference, I'm in a pnpm monorepo + moduleResolution bundler.

**Comment by Princesseuh** [comment]
> Experiencing a similar issue with `.astro` files. On vscode startup everything looks good, but when I create a new component file it no longer loads it inside intellisense until I restart vscode again. Astro runtime and builds are working fine. Will try to share a repro as soon as I can, but for reference, I'm in a pnpm monorepo + moduleResolution bundler.

What version of the extension are you using? Most of these issues should've been fixed in the last version (2.1.3)

**Comment by joshuaaron** [comment]
Have a similar issue. Using the astro vscode extension v2.3.3, astro v3.1.0. 
Can replicate with/without moduleResolution set to nodenext/node16 and `.astro` files are not working whereas `.tsx` are:

<img width="292" alt="Screen Shot 2023-09-20 at 10 01 12 PM" src="https://github.com/withastro/language-tools/assets/13953685/21f71cdd-8ce0-42fd-a6a7-4a3370ea2863">

<img width="430" alt="Screen Shot 2023-09-20 at 10 02 23 PM" src="https://github.com/withastro/language-tools/assets/13953685/616ce9ca-1a73-4965-9b3c-a0e47908698f">

**Comment by happypath-digital** [comment]
Same issue, I disabled the official Astro VS code extension and used a different one. Problem went away

**Comment by valler** [comment]
I have the same issue and created a [repro repo](https://github.com/valler/withastro-language-tools-issue-584-repro-repo).

A minimal build on my end requires a vite resolve alias and no `tsconfig.json` at all.

I need a `tsconfig.json` with configured paths, if i want to type-check with `astro check`, and it works just fine.

I also have projects where the error does not occur. As of now I can't explain why it is working in some projects but not in others.

**Comment by SeaRoll** [comment]
Anyone still with this issue? I've literally tried everything including having the astro files in include, but still error. it seems to be fine if it's like one level down from src, but as soon as it's deeper than that, it fails. It seems to be working again if restarting vs code, but it's really annoying and thinking of just switching to something else if this prevails.

**Comment by roybarber** [comment]
I had this issue when defining paths in my tsconfig. 

To fix use a dot for baseUrl not a slash

heres a copy of my `tsconfig.json`

```
{
	"extends": "astro/tsconfigs/base",
	"compilerOptions": {
		"strictNullChecks": true,
		"allowJs": true,
		"baseUrl": ".",
		"paths": {
			"@/*": [
				"src/*"
			],
			"@components/*": [
				"src/components/*"
			],
			"@assets/*": [
				"src/assets/*"
			],
			"@layouts/*": [
				"src/layouts/*"
			],
			"@css/*": [
				"src/styles/*"
			],
			"@lib/*": [
				"src/lib/*"
			]
		},
		"jsx": "preserve"
	}
}
```

**Comment by frontendkris** [comment]
I fixed all TS errors related to .astro files by upgrading typescript in my project to the latest version (4.4 to 5.4). Check out if you also have it outdated. :)

**Comment by Psypher1** [comment]
> I had this issue when defining paths in my tsconfig.
> 
> To fix use a dot for baseUrl not a slash
> 
> heres a copy of my `tsconfig.json`
> 
> ```
> {
> 	"extends": "astro/tsconfigs/base",
> 	"compilerOptions": {
> 		"strictNullChecks": true,
> 		"allowJs": true,
> 		"baseUrl": ".",
> 		"paths": {
> 			"@/*": [
> 				"src/*"
> 			],
> 			"@components/*": [
> 				"src/components/*"
> 			],
> 			"@assets/*": [
> 				"src/assets/*"
> 			],
> 			"@layouts/*": [
> 				"src/layouts/*"
> 			],
> 			"@css/*": [
> 				"src/styles/*"
> 			],
> 			"@lib/*": [
> 				"src/lib/*"
> 			]
> 		},
> 		"jsx": "preserve"
> 	}
> }
> ```

I am still getting this issue, and my tsconfig looks exactly like this. I am running astro 3.2.4 and no typescript

**Comment by Princesseuh** [comment]
I believe there's a lot of confusion here on what this issue is, some people are encountering this because Astro files are not included in their TypeScript project, which well, makes a lot of sense (we could most likely warn when that happens, for sure!), but is not really a bug.

Other are encountering this because they're using `moduleResolution: 'node16'` which, while it seems to work now, also is the wrong option to use with Astro. The files in (most parts) of your Astro projects are handled by a bundler, as such you should always be using `moduleResolution: 'bundler'` (which is what is included in all our presets)

I'll close this issue for now, since the node16 case has been resolved. If this happens again, please open another issue (with a reproduction.)

**Comment by Wuzoobia** [comment]
This is what worked for me after hours of searching...

**This Throws the Error**
import Box from '@mui/material/Box';
import { openAISolutionsText } from './openaiSolutions';
import { tables } from './touchy/tables';

**This also threw the Same Error**
import Box from '@mui/material/Box';
import { openAISolutionsText } from '@/openaiSolutions';
import { tables } from '@touchy/tables';

**This Fixed It.**
import Box from '@mui/material/Box';
import { openAISolutionsText } from '@/lib/touchy/openaiSolutions';
import { tables } from '@/lib/touchy/tables';

adding the file path fixed it for me....
