### ISSUE TITLE
🐛 BUG: @astrojs/check breaks import from specific file

### ISSUE THREAD

**Issue by lodmfjord** [withastro/language-tools#778]
### Describe the Bug

A path like this:
"@layouts/*": ["./src/layouts/*"],

is not recognized

### Steps to Reproduce

Clone this repo and checkout this PR:
https://github.com/lodmfjord/binday/pull/24

**Comment by Princesseuh** [comment]
This should be fixed in the latest version of the extension.

**Comment by CodeVxDev** [comment]
Not fixed. Still, the issue persists with Astro vs code extension's latest version, v2.7.3. Downgrading to 2.6.3 works.
tsconfig:
```json
"paths": {
      "@/components/*": ["src/components/*.astro"]
 }
```

**Comment by Princesseuh** [comment]
Arf, unfortunate. It seems like the fix worked for the exports use case, but it seems like there's still a problem with aliases in certain contexts.

**Comment by Princesseuh** [comment]
> ```json
> "paths": {
>       "@/components/*": ["src/components/*.astro"]
>  }
> ```

This example actually works just fine for me:
<img width="841" alt="image" src="https://github.com/withastro/language-tools/assets/3019731/d8ccc288-5167-4dc5-b0ce-c55c99fda84e">

Is there more details you can share?

**Comment by CodeVxDev** [comment]
It works for me, too, after upgrading to version 2.7.4. Version 2.7.0, 2.7.1 and 2.7.3 have some problems.
